### ISSUE TITLE
Implement glob support for Windows shells (which don't do this themselves)

### ISSUE THREAD

**Issue by tc-ying** [wireservice/csvkit#634]
Is there a way to group " *.csv " in a directory by --filenames ? If I pass the CSVs into csvstack using stdin, then their group names become <stdin>.

Forgive this newbie question.

**Comment by jpmckinney** [comment]
Can you share the complete command that you're running?

**Comment by yingtc** [comment]
Since this is not permissible — csvstack --filenames "*.csv"

Let's do it in windows command : type "to_append*.csv" | csvstack --filenames "master.csv" -

Output is something like :

group,header1,header2
master.csv,col1,col2
<stdin>,col1,col2
<stdin>,col1,col2

Can't figure how to stack a batch of CSVs at one command.

**Comment by jpmckinney** [comment]
Why isn't `csvstack --filenames "*.csv"` permissible?

If the file comes from stdin, then it doesn't have a filename. That's just UNIX; csvkit can't fix that.

**Comment by yingtc** [comment]
Using wildcard file names generates "error: You must specify at least two files to stack."

Its seems most csvkit commands do not accept wildcard file arguments. It makes batch csvstack less convenient coz I can't figure out a FOR... DO loop for csvstack.

**Comment by jpmckinney** [comment]
That error no longer exists in the current code base. Try the latest csvkit:

    pip install --upgrade -e git+git://github.com/onyxfish/csvkit.git@master#egg=csvkit

I can re-open if it still doesn't work with the latest version.

**Comment by yingtc** [comment]
It now works with ONE argument :+1:  , but if that argument is : 

INPUT – **csvstack "*.csv"**
OUTPUT – **[Errno 22] Invalid argument: '*.csv'**

Accepting wildcard argument seems to require fundamental program change.

**Comment by jpmckinney** [comment]
What operating system are you on?

**Comment by yingtc** [comment]
oops Win7 32-bit unfortunately

**Comment by yingtc** [comment]
users may switch to run .sh scripts in windows...

shopt -s nullglob
files=(*.csv)
csvstack "${files[@]}" > merged.csv

done.

**Comment by ilovefreesw** [comment]
2024 and still doesn't work
![image](https://github.com/wireservice/csvkit/assets/77317006/4c2b1941-e233-4593-89f9-a9418247f3ee)

**Comment by jpmckinney** [comment]
We can do something like Click did: https://github.com/pallets/click/pull/1830/files
